class Language {
  final int id;
  final String name;
  final String languageCode;

  const Language(this.id, this.name, this.languageCode);


}

const List<Language> getLanguages = <Language>[
  Language(1,'albanian','sq'),
  Language(2,'arabic','ar'),
  Language(3,'belarusian','be'),
  Language(4,'bengali','bn'),
  Language(5,'bulgarian','bg'),
  Language(6,'catalan','ca'),
  Language(7,'chinese','zh'),
  Language(8,'croatian','hr'),
  Language(9,'czech','cs'),
  Language(10,'danish','da'),
  Language(11,'dutch','nl'),
  Language(12,'english','en'),
  Language(13,'esperanto','eo'),
  Language(14,'estonian','et'),
  Language(15,'finnish','fi'),
  Language(16,'french','fr'),
  Language(17,'galician','gl'),
  Language(18,'georgian','ka'),
  Language(19,'german','de'),
  Language(20,'greek','el'),
  Language(21,'gujarati','gu'),
  Language(22,'haitian_creole','ht'),
  Language(23,'hebrew','he'),
  Language(24,'hindi','hi'),
  Language(25,'hungarian','hu'),
  Language(26,'icelandic','is'),
  Language(27,'indonesian','id'),
  Language(28,'irish','ga'),
  Language(29,'italian','it'),
  Language(30,'japanese','ja'),
  Language(31,'kannada','kn'),
  Language(32,'korean','ko'),
  Language(33,'latvian','lv'),
  Language(34,'lithuanian','lt'),
  Language(35,'macedonian','mk'),
  Language(36,'malay','ms'),
  Language(37,'maltese','mt'),
  Language(38,'marathi','mr'),
  Language(39,'norwegian','no'),
  Language(40,'persian','fa'),
  Language(41,'polish','pl'),
  Language(42,'portuguese','pt'),
  Language(43,'romanian','ro'),
  Language(44,'russian','ru'),
  Language(45,'slovak','sk'),
  Language(46,'slovenian','sl'),
  Language(47,'spanish','es'),
  Language(48,'swahili','sw'),
  Language(49,'swedish','sv'),
  Language(50,'tagalog','tl'),
  Language(51,'tamil','ta'),
  Language(52,'telugu','te'),
  Language(53,'thai','th'),
  Language(54,'turkish','tr'),
  Language(55,'ukrainian','uk'),
  Language(56,'urdu','ur'),
  Language(57,'vietnamese','vi'),
  Language(58,'welsh','cy'),

];